#!/bin/sh

if [ "$#" -ne 2 ]
then
  echo "Syntax: usage-mon <pid of process> <name of output>"
fi

export PID=$1
export FILENAME=$HOME/.usage-mon/$2.$1.dat

if [ ! -d "$HOME/.usage-mon" ]
then
  mkdir $HOME/.usage-mon
fi

if [ -f "$FILENAME" ]
then
  rm $FILENAME
fi

while ps -p $PID > /dev/null
do 
  top -p $PID -bn 1 | egrep '^[0-9]+' | awk -v now=$(date +%s) '{print now,$6,$9}' >> $FILENAME
done
