global_costmap:
  update_frequency: 1.0
  publish_frequency: 1.0
  transform_tolerance: 0.5
  width: 10
  height: 10
  resolution: 0.025
  static_map: false
  rolling_window: false
  plugins:
    - {name: static_layer,           type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,         type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
  inflation_layer:
    cost_scaling_factor: 3.0
    inflation_radius: 0.4
